# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
# For token set GITHUB_TOKEN env var or pass via --github-token
owner = "apache"
repo = "arrow-rs"

[changelog]
# Otherwise it removes the left padding in the license header
trim = false

header = """
<!---
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

# Changelog
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version %}
## [{{ version }}]({{ self::remote_url() }}/tree/{{ version }}) - ({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}
## [unreleased]
{% endif %}
[Full Changelog]({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }})
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
  {%- for commit in commits %}
- {% if commit.remote.pr_title %}{{ commit.remote.pr_title | trim }}{% else %}{{ commit.message | split(pat="\n") | first | upper_first | trim }}{% endif %}\
    {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
    {% if commit.remote.pr_number %} in \
      [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
    {%- endif -%}
  {% endfor %}
{% endfor %}
"""

[git]
# We don't use conventional commits
conventional_commits = false
filter_unconventional = false
require_conventional = false

# To make backport releases easier
use_branch_tags = true
# Ignoring rc tags
tag_pattern = "^\\d+\\.\\d+\\.\\d+$"

commit_parsers = [
    # Grouping based on PR labels
    { field = "remote.pr_labels", pattern = "api-change", group = "<!-- 0 -->Breaking changes" },
    { field = "remote.pr_labels", pattern = "security", group = "<!-- 1 -->Security fixes" },
    { field = "remote.pr_labels", pattern = "enhancement", group = "<!-- 2 -->Enhancements" },
    { field = "remote.pr_labels", pattern = "bug", group = "<!-- 3 -->Bug fixes" },
    { field = "remote.pr_labels", pattern = "performance", group = "<!-- 4 -->Performance improvements" },
    { field = "remote.pr_labels", pattern = "documentation", group = "<!-- 5 -->Documentation updates" },
    { field = "remote.pr_labels", pattern = "development-process", skip = true },
    # We could have a visible section for dependency updates if we want
    { field = "remote.pr_labels", pattern = "auto-dependencies", skip = true },
    # Ideally we minimize this last section as much as possible by ensuring PRs
    # are labelled as above
    { message = ".*", group = "<!-- 6 -->Miscellaneous" },
]
sort_commits = "newest"
