---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      # Thrift version needs to match the version of the thrift-compiler used to generate code,
      # and therefore this dependency requires a more manual upgrade
      #
      # Additionally the thrift-compiler version available in standard repos tends to lag
      # the latest release significantly, and so updating to the latest version adds friction
      - dependency-name: "thrift"
