// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Fuzz Tests for predicate evaluation in the parquet reader

use arrow_array::{Array, ArrayRef, Int8Array, Int64Array, RecordBatch, StringViewArray};
use bytes::Bytes;
use parquet::arrow::ArrowWriter;
use parquet::file::metadata::{PageIndexPolicy, ParquetMetaData, ParquetMetaDataReader};
use parquet::file::page_index::offset_index::PageLocation;
use parquet::file::properties::WriterProperties;
use std::sync::{Arc, OnceLock};

#[tokio::test]
async fn test_foo() {}

/// Ensures the parquet file generated by `three_column_parquet` has the expected
/// layout (number of row groups, pages, etc.):
/// ```text
///                 DataPages
///
///       0   ┌───────┐  ┌───────┐  ┌───────┐
///           │       │  │       │  │       │
///           │       │  │       │  │       │
///           │       │  │       │  │       │
///           │       │  │       │  │       │
///      500  └───────┘  │       │  │       │
///           ┌───────┐  │       │  │       │
///           │       │  │       │  │       │
///           │       │  │       │  │       │
///           │       │  │       │  │       │
///           │       │  │       │  └───────┘
///           └───────┘  │       │  ┌───────┐
///           ┌───────┐  │       │  │       │
///           │       │  │       │  └───────┘
///           │       │  │       │  ┌───────┐
///           │       │  │       │  │       │
///           │       │  │       │  │       │
///           └───────┘  │       │  │       │
///           ┌───────┐  │       │  │       │
///           │       │  │       │  │       │
///           │       │  │       │  └───────┘
///           │       │  │       │  ┌───────┐
///           │       │  │       │  │       │
///           └───────┘  └───────┘  └───────┘
///
///
///             int8       int64      utf8
///
///```
#[test]
fn test_verify_parquet_layout() {
    let parquet = three_column_parquet();
    let metadata = ParquetMetaDataReader::new()
        .with_page_index_policy(PageIndexPolicy::Required)
        .parse_and_finish(&parquet)
        .unwrap();
    // assume a single row group
    assert_eq!(metadata.num_row_groups(), 1);

    let int8_locations = page_locations(0, 1, &metadata);
    assert_eq!(
        page_row_offsets(int8_locations),
        vec![0, 256, 512, 768],
        "int8 locations: {int8_locations:?}"
    );
    /*
       let int64_offsets = page_row_offsets(0, 1, &metadata);
       assert_eq!(int64_offsets, vec![0, 256, 512, 768]);

       let utf8_offsets = page_row_offsets(0, 2, &metadata);
       assert_eq!(utf8_offsets, vec![0, 256, 512, 768]);

    */
}

/// returns a vector of the [`PageLocation`]s for each data page in the specified column
fn page_locations(
    row_group_index: usize,
    column_index: usize,
    metadata: &ParquetMetaData,
) -> &[PageLocation] {
    let offset_index = metadata.offset_index().expect("No offset index");
    offset_index[row_group_index][column_index].page_locations()
}

/// returns a vector of row offsets for each of the location pages
fn page_row_offsets(page_locations: &[PageLocation]) -> Vec<i64> {
    page_locations
        .iter()
        .map(|loc| loc.first_row_index)
        .collect()
}

/// Return a parquet file with three columns: int8, int64, utf8view
///
/// The page layout is designed to test predicate pushdown in various scenarios
/// such as when pages are skipped entirely, when pages have mixed selectivity,
/// etc.
///
/// Values (with nulls):
/// | int8 | int64 | utf8view       |
/// |------|-------|------------|
/// | 0    | 0     | "row 0:"  |
/// | 1    | 10    | "row 1:"  |
/// | ...  | ...   | ...        |
/// | 255  | 2550  | "row 255:"|
/// | 232    | 10000 | "row 1000:"|
///
fn three_column_parquet() -> Bytes {
    static PARQUET_BYTES: OnceLock<Bytes> = OnceLock::new();
    PARQUET_BYTES
        .get_or_init(|| {
            let int8_values = (0..1000).map(|x| {
                if x % 17 == 0 {
                    None
                } else {
                    Some((x % 256) as i8)
                }
            });
            let int8: ArrayRef = Arc::new(int8_values.collect::<Int8Array>());

            let int64_values = (0..1000).map(|x| {
                if x % 19 == 0 {
                    None
                } else {
                    Some(x as i64 * 10)
                }
            });
            let int64: ArrayRef = Arc::new(int64_values.collect::<Int64Array>());

            let utf8_values = (0..1000)
                .map(|x| {
                    if x % 23 == 0 {
                        None
                    } else {
                        Some(format!("row {}:", x))
                    }
                })
                .collect::<StringViewArray>();

            let utf8view: ArrayRef = Arc::new(
                (0..1000)
                    .map(|x| {
                        if x % 23 == 0 {
                            None
                        } else {
                            Some(format!("row {}:", x))
                        }
                    })
                    .collect::<StringViewArray>(),
            );

            let batch = RecordBatch::try_from_iter(vec![
                ("int8", int8),
                ("int64", int64),
                ("utf8view", utf8view),
            ])
            .unwrap();

            // Configure writer properties
            let props = WriterProperties::builder()
                .set_max_row_group_size(256)
                .build();

            let mut output = vec![];
            let mut writer =
                ArrowWriter::try_new(&mut output, batch.schema(), Some(props)).unwrap();
            writer.write(&batch).unwrap();
            writer.close().unwrap();
            Bytes::from(output)
        })
        .clone()
}

/// Test case -- the idea is to read a parquet file with various predicates
/// and verify that the results are as expected.
///
/// For example
/// ```text
///                    DataPages
///
///  Row Offsets ┌───────┐  ┌───────┐  ┌───────┐
///              │       │  │       │  │       │
///              │ SKIP  │  │       │  │       │
///              │       │  │       │  │       │
///              │       │  │       │  │       │
///              └───────┘  │       │  │       │
///              ┌───────┐  │       │  │       │
///         ┌ ─ ─│─ ─ ─ ─│─ ┼ ─ ─ ─ ┼ ─│─ ─ ─ ─│─ ─ ─
///              │       │  │       │  │       │     │
///         └ ─ ─│─ ─ ─ ─│─ ┼ ─ ─ ─ ┼ ─│─ ─ ─ ─│─ ─ ─
///              │       │  │       │  └───────┘
///              └───────┘  │       │  ┌───────┐
///              ┌───────┐  │       │  │ SKIP  │
///              │       │  │       │  └───────┘
///              │ SKIP  │  │       │  ┌───────┐
///              │       │  │       │  │       │
///              │       │  │       │  │       │
///              └───────┘  │       │  │       │
///         ┌ ─ ─┌───────┐─ ┼ ─ ─ ─ ┼ ─│─ ─ ─ ─│─ ─ ─ ┐
///              │       │  │       │  │       │
///         │    │       │  │       │  └───────┘      │
///              │       │  │       │  ┌───────┐
///         └ ─ ─│─ ─ ─ ─│─ ┼ ─ ─ ─ ┼ ─│─ ─ ─ ─│─ ─ ─ ┘
///              └───────┘  └───────┘  └───────┘
///
///
///                int8       int64      utf8
///
/// ```
///
struct Test {
    parquet: Bytes,
}

impl Test {
    async fn run() {
        todo!();
    }
}
