// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! Fuzz Tests for predicate evaluation in the parquet reader

use arrow_array::cast::AsArray;
use arrow_array::types::Int64Type;
use arrow_array::{
    Array, ArrayRef, Int8Array, Int64Array, RecordBatch, StringViewArray, UInt8Array,
};
use arrow_select::concat::concat_batches;
use bytes::Bytes;
use parquet::arrow::arrow_reader::{
    ArrowPredicateFn, ParquetRecordBatchReader, ParquetRecordBatchReaderBuilder, RowFilter,
    RowSelection,
};
use parquet::arrow::{ArrowWriter, ProjectionMask};
use parquet::basic::Compression;
use parquet::file::metadata::{PageIndexPolicy, ParquetMetaData, ParquetMetaDataReader};
use parquet::file::page_index::offset_index::PageLocation;
use parquet::file::properties::WriterProperties;
use parquet::file::reader::ChunkReader;
use std::ops::Range;
use std::sync::{Arc, OnceLock};

/// Ensures the parquet file generated by `three_column_parquet` has the expected
/// layout (number of row groups, pages, etc.):
/// ```text
///                      DataPages
///
///
///         0 ┌───────┐    0 ┌───────┐      0 ┌───────┐
///           │       │      │       │        │       │
///           │       │      │       │        │       │
///           │       │      │       │        └───────┘
///           │       │      │       │    184 ┌───────┐
///           │       │      └───────┘        │       │
///           │       │  264 ┌───────┐        │       │
///           │       │      │       │        │       │
///           │       │      │       │        └───────┘
///           │       │      │       │    359 ┌───────┐
///           │       │      └───────┘        │       │
///           └───────┘  528 ┌───────┐        │       │
///      532  ┌───────┐      │       │        │       │
///           │       │      │       │        └───────┘
///           │       │      │       │    708 ┌───────┐
///           │       │      │       │        │       │
///           │       │      └───────┘        │       │
///           │       │  792 ┌───────┐        │       │
///           │       │      │       │        └───────┘
///           │       │      │       │    883 ┌───────┐
///           │       │      │       │        │       │
///           │       │      │       │        │       │
///           │       │      │       │        │       │
///           └───────┘      └───────┘        └───────┘
///
///             uint8          int64              utf8view
///```
#[test]
fn test_verify_parquet_layout() {
    let parquet = three_column_parquet();
    let metadata = ParquetMetaDataReader::new()
        .with_page_index_policy(PageIndexPolicy::Required)
        .parse_and_finish(&parquet)
        .unwrap();
    // assume a single row group
    assert_eq!(metadata.num_row_groups(), 1);

    let int8_locations = page_locations(0, 0, &metadata);
    assert_eq!(
        page_row_offsets(int8_locations),
        [0, 532],
        "int8 locations: {int8_locations:?}"
    );

    let int64_locations = page_locations(0, 1, &metadata);
    assert_eq!(
        page_row_offsets(int64_locations),
        [0, 264, 528, 792],
        "int64 locations: {int64_locations:?}"
    );

    let utf8_locations = page_locations(0, 2, &metadata);
    assert_eq!(
        page_row_offsets(utf8_locations),
        [0, 184, 359, 534, 708, 883],
        "utf8 locations: {utf8_locations:?}"
    );
}

/// returns a vector of the [`PageLocation`]s for each data page in the specified column
fn page_locations(
    row_group_index: usize,
    column_index: usize,
    metadata: &ParquetMetaData,
) -> &[PageLocation] {
    let offset_index = metadata.offset_index().expect("No offset index");
    offset_index[row_group_index][column_index].page_locations()
}

/// returns a vector of row offsets for each of the location pages
fn page_row_offsets(page_locations: &[PageLocation]) -> Vec<i64> {
    page_locations
        .iter()
        .map(|loc| loc.first_row_index)
        .collect()
}

/// Return a parquet file with three columns: int8, int64, utf8view
///
/// See comments on `test_verify_parquet_layout` for the expected layout
/// of the resulting parquet file.
fn three_column_parquet() -> Bytes {
    static PARQUET_BYTES: OnceLock<Bytes> = OnceLock::new();
    PARQUET_BYTES
        .get_or_init(|| {
            let batch = three_column_batch();
            // Configure writer properties
            let props = WriterProperties::builder()
                .set_dictionary_enabled(false)
                // We can't set datapage limits per column, so use different sized columns
                // to achieve the desired layout
                .set_data_page_size_limit(2000) // bytes
                .set_compression(Compression::UNCOMPRESSED)
                .set_write_batch_size(1)
                .build();

            let mut output = vec![];
            let mut writer =
                ArrowWriter::try_new(&mut output, batch.schema(), Some(props)).unwrap();
            writer.write(&batch).unwrap();
            writer.close().unwrap();
            Bytes::from(output)
        })
        .clone()
}

fn three_column_batch() -> RecordBatch {
    static BATCH: OnceLock<RecordBatch> = OnceLock::new();
    BATCH
        .get_or_init(|| {
            let int8_values = (0..1000).map(|x| {
                if x % 17 == 0 {
                    None
                } else {
                    Some((x % 256) as u8)
                }
            });
            let int8: ArrayRef = Arc::new(int8_values.collect::<UInt8Array>());

            let int64_values = (0..1000).map(|x| {
                if x % 19 == 0 {
                    None
                } else {
                    Some(x as i64 * 10)
                }
            });
            let int64: ArrayRef = Arc::new(int64_values.collect::<Int64Array>());

            let utf8_values = (0..1000)
                .map(|x| {
                    if x % 23 == 0 {
                        None
                    } else {
                        Some(format!("Row {}:", x))
                    }
                })
                .collect::<StringViewArray>();

            let utf8view: ArrayRef = Arc::new(StringViewArray::from(utf8_values));

            RecordBatch::try_from_iter(vec![
                ("int8", int8),
                ("int64", int64),
                ("utf8view", utf8view),
            ])
            .unwrap()
        })
        .clone()
}

#[test]
fn test_manual_single_selection() {
    Test {
        parquet: three_column_parquet(),
        selections: vec![190..400],
    }
    .run()
}

/// Test case -- the idea is to read a parquet file with various predicates
/// and verify that the results are as expected.
///
/// For example, this lets us verify that reading with a selection predicate
/// that skips certain rows (and thus pages) returns the expected results.
/// ```text
///         0 ┌───────┐    0 ┌───────┐      0 ┌───────┐
///           │       │      │       │        │ SKIP  │
///           │       │      │ SKIP  │        │       │
///           │       │      │       │        └───────┘
///           │       │      │       │    184 ┌───────┐
///           │       │      └───────┘        │       │
///           │       │  264 ┌───────┐        │       │
///        ┌ ─│─ ─ ─ ─│─ ─ ─ ┼ ─ ─ ─ ┼ ─ ─ ─ ─│─ ─ ─ ─│─ ┐
///           │       │      │       │        └───────┘       Selection
///        │  │       │      │       │    359 ┌───────┐  │
///         ─ ┼ ─ ─ ─ ┼ ─ ─ ─└───────┘─ ─ ─ ─ ┼ ─ ─ ─ ┼ ─
///           └───────┘  528 ┌───────┐        │       │
///      532  ┌───────┐      │       │        │       │
///           │       │      │ SKIP  │        └───────┘
///           │       │      │       │    708 ┌───────┐
///           │       │      │       │        │       │
///           │       │      └───────┘        │       │
///        ┌ ─│─ ─ ─ ─│─ ─9─ ┬───────┬ ─ ─ ─ ─│─ ─ ─ ─│─ ┐   Selection
///           │       │      │       │        └───────┘
///        │  │       │      │       │    883 ┌───────┐  │
///         ─ ┼ ─ ─ ─ ┼ ─ ─ ─│─ ─ ─ ─│─ ─ ─ ─ ┼ ─ ─ ─ ┼ ─
///           │       │      │       │        │       │
///           │       │      │       │        │       │
///           └───────┘      └───────┘        └───────┘
///
///             int8           int64              utf8view
/// ```
///
struct Test {
    /// The input parquet file
    parquet: Bytes,
    /// which selections to make -- each selection is a range of row indices to
    /// include The tests verify that only rows within these ranges are returned
    /// and select
    selections: Vec<Range<usize>>,
}

impl Test {
    /// Basic idea is to evaluate the selections in several different ways and compare the results
    fn run(&self) {
        for projection in self.all_projections() {
            println!("projection: {:?}", projection);
            let expected = self.expected(&projection);

            for batch_size in [100, 217, 8192] {
                println!("  batch size: {}", batch_size);

                self.run_inner(projection, batch_size, &expected, |b| {
                    self.add_predicate_row_selection(b)
                });

                self.run_inner(projection, batch_size, &expected, |b| {
                    self.add_predicate_row_filter_int8(b)
                });
            }
        }
    }

    /// Create a reader with the specified projection and batch size,
    /// and function F to apply the selection predicates.
    ///
    /// Reads all rows and verify the results match expected
    fn run_inner<F>(
        &self,
        projection: &[&str],
        batch_size: usize,
        expected: &RecordBatch,
        add_predicate: F,
    ) where
        F: Fn(ParquetRecordBatchReaderBuilder<Bytes>) -> ParquetRecordBatchReaderBuilder<Bytes>,
    {
        let builder = self
            .builder_with_projection(projection)
            .with_batch_size(batch_size);
        let reader = add_predicate(builder).build().unwrap();
        let actual = self.collect_to_batch(reader);

        assert_eq!(
            expected, &actual,
            "selections: {projection:?}, batch size: {batch_size}\n\
                            expected:\n\
                            \n\
                            {expected:#?}\n\
                            \n\
                            {actual:#?}",
        );
    }

    /// A list of columns to project
    fn all_projections(&self) -> &[&[&str]] {
        &[
            &["int8"],
            //["int64"],
            //["utf8view"], ["int8", "int64"], ["int64", "utf8view"], ["int8", "utf8view"],
            &["int8", "int64", "utf8view"],
        ]
    }

    /// Return a ParquetRecordBatchReaderBuilder ready to read the parquet file
    fn builder_with_projection(
        &self,
        projection: &[&str],
    ) -> ParquetRecordBatchReaderBuilder<Bytes> {
        let builder = ParquetRecordBatchReaderBuilder::try_new(self.parquet.clone()).unwrap();

        let projection = ProjectionMask::columns(
            builder.metadata().file_metadata().schema_descr(),
            projection.iter().cloned(),
        );
        builder.with_projection(projection)
    }

    /// Apply the selections to the three_column_batch to get the expected result
    fn expected(&self, columns: &[&str]) -> RecordBatch {
        let batch = three_column_batch();
        let indices = columns
            .iter()
            .map(|col_name| batch.schema().index_of(col_name).unwrap())
            .collect::<Vec<_>>();

        let batch = batch.project(&indices).unwrap();
        let batches: Vec<_> = self
            .selections
            .iter()
            .map(|range| {
                // collect expected rows from the three_column_batch
                batch.slice(range.start, range.end - range.start)
            })
            .collect();

        concat_batches(&batch.schema(), &batches).unwrap()
    }

    fn collect_to_batch(&self, mut reader: ParquetRecordBatchReader) -> RecordBatch {
        let mut batches = vec![];
        while let Some(batch) = reader.next() {
            let batch = batch.unwrap();
            batches.push(batch);
        }
        let schema = batches[0].schema();
        concat_batches(&schema, &batches).unwrap()
    }

    // ------------------
    // Below are different predicates are added to the reader. Note these
    // methods all select the same selections, just in different ways.
    // ------------------

    /// Add a predicate to the reader that selects only the specified rows
    fn add_predicate_row_selection<T: ChunkReader>(
        &self,
        builder: ParquetRecordBatchReaderBuilder<T>,
    ) -> ParquetRecordBatchReaderBuilder<T> {
        let num_rows = builder.metadata().file_metadata().num_rows() as usize;
        let selection =
            RowSelection::from_consecutive_ranges(self.selections.clone().into_iter(), num_rows);
        builder.with_row_selection(selection)
    }

    /// Add a predicate to the reader via a predicate on the "int64" column
    fn add_predicate_row_filter_int8<T: ChunkReader>(
        &self,
        builder: ParquetRecordBatchReaderBuilder<T>,
    ) -> ParquetRecordBatchReaderBuilder<T> {
        let mask = ProjectionMask::columns(
            builder.metadata().file_metadata().schema_descr(),
            vec!["int8"],
        );
        let filter = RowFilter::new(vec![Box::new(ArrowPredicateFn::new(mask, |array| todo!()))]);
        builder.with_row_filter(filter)
    }
}
