blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/apache/arrow-rs/discussions
    about: Have a question or want to discuss an idea? Please open a GitHub Discussion.
