# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

arrow-core:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow/**/*"
      - "arrow-array/**/*"
      - "arrow-buffer/**/*"
      - "arrow-data/**/*"
      - "arrow-integration-test/**/*"
      - "arrow-integration-testing/**/*"
      - "arrow-schema/**/*"

arrow-kernels:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-arith/**/*"
      - "arrow-cast/**/*"
      - "arrow-select/**/*"
      - "arrow-string/**/*"
      - "arrow-ord/**/*"
      - "arrow-cmp/**/*"

arrow-avro:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-avro/**/*"

arrow-flight:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-flight/**/*"

parquet:
  - changed-files:
    - any-glob-to-any-file:
      - "parquet/**/*"
      - "parquet_derive/**/*"
      - "parquet_derive_test/**/*"
      - "parquet-geospatial/**/*"

parquet-variant:
  - changed-files:
    - any-glob-to-any-file:
      - "parquet-variant/**/*"
      - "parquet-variant-compute/**/*"
      - "parquet-variant-json/**/*"

arrow-csv:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-csv/**/*"

arrow-ipc:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-ipc/**/*"

arrow-json:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-json/**/*"

arrow-pyarrow:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-pyarrow/**/*"
      - "arrow-pyarrow-testing/**/*"
      - "arrow-pyarrow-integration-testing/**/*"

arrow-row:
  - changed-files:
    - any-glob-to-any-file:
      - "arrow-row/**/*"
